[project]
name = "productivepro"
version = "0.1.0"
description = "A productivity-boosting tool with PDF processing and study features"
requires-python = ">=3.11"

dependencies = [
    "pdfplumber>=0.11.7",
    "PyPDF2>=3.0.1",
    "trafilatura>=2.0.0",
]
